name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Get dependencies
      run: go mod tidy
      
    - name: Run tests
      run: go test -v
      
    - name: Run tests with race detector
      run: go test -race -v
      
    - name: Build
      run: go build -v SSTableKeys.go
      
    - name: Run linting (if available)
      run: |
        if command -v golangci-lint &> /dev/null; then
          golangci-lint run
        else
          echo "golangci-lint not available, skipping"
        fi